version: 0.0
os: linux
files:
  - source: /
    destination: /var/application

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  AfterInstall:
    - location: scripts/install.sh
      timeout: 900
      runas: root
  ApplicationStart:
    - location: scripts/run.sh
      timeout: 300
      runas: ec2-user