version: 0.1

phases:
  install:
    commands:
      - printenv
      - npm install

  build:
    commands:
      - npm test
      - mkdir -p build
      - zip -x '*.git*' -r build/app.zip .

artifacts:
  files:
    - build/app.zip
  discard-paths: yes