version: 0.1

phases:
  install:
    commands:
      - printenv
      - npm install

  build:
    commands:
      - npm test
      - rm -rf .git
      - rm -rf node_modules

artifacts:
  files:
    - '**/*'
  discard-paths: no